[package]
name = "rustreg"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "2.0.13"
solana-client = "2.0.13"
solana-program = "2.0.13"
solana-idlgen = { git = "https://github.com/deanmlittle/solana-idlgen.git" }
bs58 = "0.5.1"
borsh = "1.5.1"